[package]
name = "bottles-server"
description = "A gRPC server for the Bottles Next Wine and Proton environment management."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository = "https://github.com/bottlesdevs/next-server/"
homepage = ""
categories = [""]
keywords = [""]
exclude = [""]

[dependencies]
bottles-core.workspace = true
tonic.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
