[package]
name = "bottles-server"
version = "0.1.0"
edition = "2021"

[dependencies]
bottles-core = { git = "https://github.com/bottlesdevs/next-core" }
tokio = { version = "1.42.0", features = ["full"] }
tonic = "0.12.3"
