[package]
name = "bottles-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.3"
tokio = { version = "1.28.2", features = ["full"] }
prost = "0.13.4"

[build-dependencies]
tonic-build = "0.12.3"
